#!/bin/zsh

# researchsdk
# Copyright 2024 Guilherme Rambo (github.com/insidegui)
# See LICENSE file for details

echo ""

function echoRed {
    echo "\033[0;31m$1\033[0m"
}
function echoYellow {
    echo "\033[0;33m$1\033[0m"
}
function echoGreen {
    echo "\033[0;32m$1\033[0m"
}


if [ ! -z $1 ]
then
    if [ ${1} = "--help" ] || [ ${1} = "-h" ]
    then
        echo "Usage: researchsdk [sdk name] [--patch-original]\n"
        echo "Specify --patch-original to also modify SDKSettings files in the original SDK to allow adhoc signing\n"
        exit 64
    fi
fi

PATCH_ORIGINAL=0
if [ ! -z $1 ]
then
    if [ ${1} = "--patch-original" ]
    then
        PATCH_ORIGINAL=1
    fi
fi
if [ ! -z $2 ]
then
    if [ ${2} = "--patch-original" ]
    then
        PATCH_ORIGINAL=1
    fi
fi

# Allow SDK name to be passed as an argument, use iphoneos as default
if [ -z "$1" ] || [ ${1} = "--patch-original" ]
then
    INPUT_SDK_NAME="iphoneos"
else
    INPUT_SDK_NAME="$1"
fi

INPUT_SDK_PATH_SYMLINK=$(xcrun --show-sdk-path --sdk $INPUT_SDK_NAME)

# Resolve symlink
INPUT_SDK_PATH=$(realpath "$INPUT_SDK_PATH_SYMLINK")

if [ ! -d "$INPUT_SDK_PATH" ]; then
    echoRed "Input SDK does not exist at $INPUT_SDK_PATH"
    echo ""
    exit 1
fi

INPUT_SDK_PATH_NO_EXT=${INPUT_SDK_PATH%.sdk}
INPUT_SDK_PATH_SYMLINK_NO_EXT=${INPUT_SDK_PATH_SYMLINK%.sdk}

RESEARCH_SDK_PATH_SYMLINK="$INPUT_SDK_PATH_SYMLINK_NO_EXT.internal.sdk"
RESEARCH_SDK_PATH="$INPUT_SDK_PATH_NO_EXT.internal.sdk"

echo "Input SDK symlink is at $INPUT_SDK_PATH_SYMLINK"
echo "Input SDK is at $INPUT_SDK_PATH"
echo "Research SDK will be created at $RESEARCH_SDK_PATH"
echo "Research SDK symlink will be created at $RESEARCH_SDK_PATH_SYMLINK"

if [ $PATCH_ORIGINAL -eq 1 ]
then
    echo "Input SDKSettings will also be patched to allow adhoc signing (--patch-original)"
fi

echo ""

if [ -d "$RESEARCH_SDK_PATH" ]; then
    echoRed "Research SDK already exists at $RESEARCH_SDK_PATH, please remove it before running this script"
    echo ""
    exit 1
fi

# Automatically continue in 5 seconds
echo ""
echoYellow "Press any key to continue, Ctrl+C to cancel..."
read

echo ""

echo "Creating Research SDK at $RESEARCH_SDK_PATH"

cp -cr "$INPUT_SDK_PATH" "$RESEARCH_SDK_PATH"

if [ ! -d "$RESEARCH_SDK_PATH" ]
then
    echo "Failed to copy SDK"
    echo ""
    exit 1
fi

echo "Creating Research SDK symlink at $RESEARCH_SDK_PATH_SYMLINK"

ln -s "$RESEARCH_SDK_PATH" "$RESEARCH_SDK_PATH_SYMLINK"

# Ensure the jj command-line tool is available
if ! command -v jj &> /dev/null
then
    echo "jj could not be found; it can be installed with 'brew install tidwall/jj/jj'"
    echo ""
    exit 1
fi

echo ""
echo "Research SDK will be available at $RESEARCH_SDK_PATH"
echo ""

INPUT_SETTINGS_JSON_PATH="$INPUT_SDK_PATH/SDKSettings.json"
INPUT_SETTINGS_PLIST_PATH="$INPUT_SDK_PATH/SDKSettings.plist"

SETTINGS_JSON_PATH="$RESEARCH_SDK_PATH/SDKSettings.json"
SETTINGS_PLIST_PATH="$RESEARCH_SDK_PATH/SDKSettings.plist"

function setJSONProperty {
    KEY=$1
    VALUE=$2
    FILEPATH=$3

    ORIGINAL_VALUE=$(jj -i "$FILEPATH" "$KEY")

    if [ -z "$ORIGINAL_VALUE" ]
    then
        echo "$KEY key not found in SDKSettings.json"
        echo ""
        exit 1
    fi

    if ! [[ $ORIGINAL_VALUE == "$VALUE" ]]; then
        echo "Setting $KEY to '$VALUE'"

        jj -i "$FILEPATH" -v "$VALUE" -O "$KEY" -o "$FILEPATH"
    else
        echo "$KEY is already '$ORIGINAL_VALUE'"
    fi
}

function appendStringToJSONProperty {
    KEY=$1
    VALUE=$2
    FILEPATH=$3

    ORIGINAL_VALUE=$(jj -i "$FILEPATH" "$KEY")

    if [ -z "$ORIGINAL_VALUE" ]
    then
        echo "$KEY key not found in SDKSettings.json"
        echo ""
        exit 1
    fi

    if ! [[ $ORIGINAL_VALUE == *"$VALUE"* ]]; then
        UPDATED_VALUE="$ORIGINAL_VALUE$VALUE"

        setJSONProperty "$KEY" "$UPDATED_VALUE" "$FILEPATH"
    else
        echo "$KEY is already '$ORIGINAL_VALUE'"
    fi
}

function setPlistProperty {
    KEY=$1
    VALUE=$2
    FILEPATH=$3

    ORIGINAL_VALUE=$(/usr/libexec/PlistBuddy -c "Print $KEY" "$FILEPATH")

    if [ -z "$ORIGINAL_VALUE" ]
    then
        echo "$KEY key not found in SDKSettings.plist"
        echo ""
        exit 1
    fi

    if ! [[ $ORIGINAL_VALUE == "$VALUE" ]]; then
        echo "Setting $KEY to '$VALUE'"

        /usr/libexec/PlistBuddy -c "Set $KEY $VALUE" "$FILEPATH"
    else
        echo "$KEY is already '$ORIGINAL_VALUE'"
    fi
}

function appendStringToPlistProperty {
    KEY=$1
    VALUE=$2
    FILEPATH=$3

    ORIGINAL_VALUE=$(/usr/libexec/PlistBuddy -c "Print $KEY" "$FILEPATH")

    if [ -z "$ORIGINAL_VALUE" ]
    then
        echo "$KEY key not found in SDKSettings.plist"
        echo ""
        exit 1
    fi

    if ! [[ $ORIGINAL_VALUE == *"$VALUE"* ]]; then
        UPDATED_VALUE="$ORIGINAL_VALUE$VALUE"

        setPlistProperty "$KEY" "$UPDATED_VALUE" "$FILEPATH"
    else
        echo "$KEY is already '$ORIGINAL_VALUE'"
    fi
}

function applySDKSettingsPatches {
    JSONPATH=$1
    PLISTPATH=$2
    TITLE=$3
    CHANGE_IDENTIFIERS=$4
    
    echo "## $TITLE SDKSettings.json"
    echo ""
    
    if [ $CHANGE_IDENTIFIERS -eq 1 ]
    then
        appendStringToJSONProperty "DisplayName" " Research" "$JSONPATH"
        appendStringToJSONProperty "MinimalDisplayName" " Research" "$JSONPATH"
        # I tried using ".research" as the suffix, but Xcode will only recognize ".internal"
        appendStringToJSONProperty "CanonicalName" ".internal" "$JSONPATH"
    fi
    
    setJSONProperty "DefaultProperties.ENTITLEMENTS_REQUIRED" "NO" "$JSONPATH"
    setJSONProperty "DefaultProperties.AD_HOC_CODE_SIGNING_ALLOWED" "YES" "$JSONPATH"
    setJSONProperty "DefaultProperties.CODE_SIGNING_REQUIRED" "NO" "$JSONPATH"
    setJSONProperty "DefaultProperties.CODE_SIGN_IDENTITY" "-" "$JSONPATH"
    
    echo ""
    
    echo "## $TITLE SDKSettings.plist"
    echo ""
    
    if [ $CHANGE_IDENTIFIERS -eq 1 ]
    then
        appendStringToPlistProperty "DisplayName" " Research" "$PLISTPATH"
        appendStringToPlistProperty "MinimalDisplayName" " Research" "$PLISTPATH"
        # I tried using ".research" as the suffix, but Xcode will only recognize ".internal"
        appendStringToPlistProperty "CanonicalName" ".internal" "$PLISTPATH"
    fi
    
    setPlistProperty ":DefaultProperties:ENTITLEMENTS_REQUIRED" "NO" "$PLISTPATH"
    setPlistProperty ":DefaultProperties:AD_HOC_CODE_SIGNING_ALLOWED" "YES" "$PLISTPATH"
    setPlistProperty ":DefaultProperties:CODE_SIGNING_REQUIRED" "NO" "$PLISTPATH"
    setPlistProperty ":DefaultProperties:CODE_SIGN_IDENTITY" "-" "$PLISTPATH"
    
    echo ""
}

applySDKSettingsPatches "$SETTINGS_JSON_PATH" "$SETTINGS_PLIST_PATH" "Research -" 1

if [ $PATCH_ORIGINAL -eq 1 ]
then
    applySDKSettingsPatches "$INPUT_SETTINGS_JSON_PATH" "$INPUT_SETTINGS_PLIST_PATH" "Original -" 0
fi

# This fixes "duplicate module definition libxml2" error
rm -Rf "$RESEARCH_SDK_PATH/usr/include/libxml2" 2>/dev/null

if [[ "$INPUT_SDK_NAME" = "iphoneos" || "$INPUT_SDK_NAME" = "iphonesimulator" ]]; then
    echo "Removing all \"API_UNAVAILABLE(ios)\" tags from SDK headers..."

    cd "$RESEARCH_SDK_PATH"
    find . -type f -name "*.h" -exec sed -i '' -e 's/ API_UNAVAILABLE(ios, watchos, tvos)//g' -e 's/ API_UNAVAILABLE(ios)//g' -e 's/ API_UNAVAILABLE(ios, tvos, watchos)//g' {} \;
    cd ..

    echo ""

    echo "Making libSwiftXPC API available on iOS..."

    # Remove the "/@available(iOS, unavailable)" annotations from the XPC Swift module
    find "$RESEARCH_SDK_PATH/usr/lib/swift/XPC.swiftmodule" -type f -name '*.swiftinterface' -exec sed -i '' '/@available(iOS, unavailable)/d' {} \;

    # Add availability annotation for iOS where needed
    find "$RESEARCH_SDK_PATH/usr/lib/swift/XPC.swiftmodule" -type f -name '*.swiftinterface' -exec sed -i '' 's/@available(macOS 14.0, macCatalyst 17.0, \*)/@available(macOS 14.0, macCatalyst 17.0, iOS 17.0, \*)/g' {} \;

    # Add availability annotation for iOS where needed (iOS 26)
    find "$RESEARCH_SDK_PATH/usr/lib/swift/XPC.swiftmodule" -type f -name '*.swiftinterface' -exec sed -i '' 's/@available(macOS 26.0, macCatalyst 26.0, \*)/@available(macOS 26.0, macCatalyst 26.0, iOS 26.0, \*)/g' {} \;

    echo ""
fi

echoGreen "Research SDK created successfully"

echo ""

echo "You can copy and paste the following into your project settings to enable the new SDK:"
echo ""
echo "SDKROOT = '$RESEARCH_SDK_PATH'"
echo ""